Change from single configuration file to folder and add secure key generation to init script

diff --git a/bin/sbu-init b/bin/sbu-init
--- a/bin/sbu-init
+++ b/bin/sbu-init
@@ -1,6 +1,7 @@
 #!/bin/bash
 
-DEFAULT_CONFIG_FILE=$HOME/.sburc
+CONFIG_DIR=$HOME/.sbu
+ENCRYPTION_KEY_LENGTH=128
 DEFAULT_BACKUP_USER=$USER
 DEFAULT_LOCAL_BACKUP_DIR=backups
 DEFAULT_BACKUP_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/backups-enabled"
@@ -46,9 +47,17 @@ if [ ! -d "$backup_script_dir" ]; then
   exit 1
 fi
 
+# Create folder for configuration files
+echo "Creating directory for configuration files '$CONFIG_DIR'..."
+mkdir -p $CONFIG_DIR
+if [ $? -ne 0 ]; then
+  echo "error: could not create configuration directory" >&2
+  exit 1
+fi
+
 # Write configuration file
-echo "Writing configuration to '$DEFAULT_CONFIG_FILE'..."
-cat << EOF > $DEFAULT_CONFIG_FILE
+echo "Writing configuration to '$CONFIG_DIR/config'..."
+cat << EOF > $CONFIG_DIR/config
 [DEFAULT]
 backup_user = $backup_user
 local_backup_dir = $local_backup_dir
@@ -56,5 +65,33 @@ backup_script_dir = $backup_script_dir
 EOF
 if [ $? -ne 0 ]; then
   echo "error: could not write configuration" >&2
+  exit 1
+fi
+
+# Store key
+keyfile="$CONFIG_DIR/key"
+echo "Generating encryption key and storing it to '$keyfile'..."
+# Create key file and allow read/write only from user
+touch $keyfile
+if [ $? -ne 0 ]; then
+  echo "error: could not create key file" >&2
+  exit 1
+fi
+chmod 600 $keyfile
+if [ $? -ne 0 ]; then
+  echo "error: could not set permissions on key file" >&2
+  exit 1
+fi
+# Write key to keyfile
+$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/sbu-keygen \
+  $ENCRYPTION_KEY_LENGTH \
+  > $keyfile
+if [ $? -ne 0 ]; then
+  echo "error: could not write key to key file" >&2
+  exit 1
+fi
+chmod 400 $keyfile
+if [ $? -ne 0 ]; then
+  echo "error: could not set permissions on key file" >&2
   exit 1
 fi
