Add directory with backup scripts

diff --git a/bin/sbu-init b/bin/sbu-init
--- a/bin/sbu-init
+++ b/bin/sbu-init
@@ -3,6 +3,7 @@
 DEFAULT_CONFIG_FILE=$HOME/.sburc
 DEFAULT_BACKUP_USER=$USER
 DEFAULT_LOCAL_BACKUP_DIR=backups
+DEFAULT_BACKUP_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/backups-enabled"
 
 # Backup user
 echo -n "User name for local backups [$DEFAULT_BACKUP_USER]: "
@@ -34,11 +35,24 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
+# Directory with backup scripts to run
+echo -n "Directory with backup scripts to run [$DEFAULT_BACKUP_SCRIPT_DIR]: "
+read backup_script_dir
+if [ -z "$backup_script_dir" ]; then
+  backup_script_dir=$DEFAULT_BACKUP_SCRIPT_DIR
+fi
+if [ ! -d "$backup_script_dir" ]; then
+  echo "error: directory '$backup_script_dir' does not exist" >&2
+  exit 1
+fi
+
 # Write configuration file
 echo "Writing configuration to '$DEFAULT_CONFIG_FILE'..."
 cat << EOF > $DEFAULT_CONFIG_FILE
+[DEFAULT]
 backup_user = $backup_user
 local_backup_dir = $local_backup_dir
+backup_script_dir = $backup_script_dir
 EOF
 if [ $? -ne 0 ]; then
   echo "error: could not write configuration" >&2
